# Assignment

### Importing libraries for the (Exploratory Data Analysis) EDA.

In [1]:
import pandas as pd
import numpy as np

### Loading the dataset

In [2]:
df = pd.read_csv("aps_failure_set.csv")

In [3]:
df

class  aa_000 ab_000      ac_000 ad_000 ae_000 af_000 ag_000 ag_001  \
0       neg   76698     na  2130706438    280      0      0      0      0   
1       neg   33058     na           0     na      0      0      0      0   
2       neg   41040     na         228    100      0      0      0      0   
3       neg      12      0          70     66      0     10      0      0   
4       neg   60874     na        1368    458      0      0      0      0   
...     ...     ...    ...         ...    ...    ...    ...    ...    ...   
59995   neg  153002     na         664    186      0      0      0      0   
59996   neg    2286     na  2130706538    224      0      0      0      0   
59997   neg     112      0  2130706432     18      0      0      0      0   
59998   neg   80292     na  2130706432    494      0      0      0      0   
59999   neg   40222     na         698    628      0      0      0      0   

      ag_002  ...   ee_002  ee_003   ee_004   ee_005   ee_006  ee_007  ee_008  \
0          0  ...  1240520  493384   721044   469792   339156  157956   73224   
1          0  ...   421400  178064   293306   245416   133654   81140   97576   
2          0  ...   277378  159812   423992   409564   320746  158022   95128   
3          0  ...      240      46       58       44       10       0       0   
4          0  ...   622012  229790   405298   347188   286954  311560  433954   
...      ...  ...      ...     ...      ...      ...      ...     ...     ...   
59995      0  ...   998500  566884  1290398  1218244  1019768  717762  898642   
59996      0  ...    10578    6760    21126    68424      136       0       0   
59997      0  ...      792     386      452      144      146    2622       0   
59998      0  ...   699352  222654   347378   225724   194440  165070  802280   
59999      0  ...   440066  183200   344546   254068   225148  158304  170384   

       ee_009 ef_000 eg_000  
0           0      0      0  
1        1500      0      0  
2         514      0      0  
3           0      4     32  
4        1218      0      0  
...       ...    ...    ...  
59995   28588      0      0  
59996       0      0      0  
59997       0      0      0  
59998  388422      0      0  
59999     158      0      0  

[60000 rows x 171 columns]

### Analyzing the size of the dataset

In [4]:
num_rows, num_columns = df.shape
print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_columns}")

Number of rows: 60000
Number of columns: 171


### Checking details of each column (datatype, number of null entries etc)

In [5]:
for column in df.columns:
    df[column].info()

<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: class
Non-Null Count  Dtype 
--------------  ----- 
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: aa_000
Non-Null Count  Dtype
--------------  -----
60000 non-null  int64
dtypes: int64(1)
memory usage: 468.9 KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ab_000
Non-Null Count  Dtype 
--------------  ----- 
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ac_000
Non-Null Count  Dtype 
--------------  ----- 
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: ad_000
Non-Null Count  Dtype 
--------------  ----- 
60000 non-null  object
dtypes: object(1)
memor

<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bo_000
Non-Null Count  Dtype 
--------------  ----- 
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bp_000
Non-Null Count  Dtype 
--------------  ----- 
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bq_000
Non-Null Count  Dtype 
--------------  ----- 
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: br_000
Non-Null Count  Dtype 
--------------  ----- 
60000 non-null  object
dtypes: object(1)
memory usage: 468.9+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 60000 entries, 0 to 59999
Series name: bs_000
Non-Null Count  Dtype 
--------------  ----- 
60000 non-null  object
dtypes: object(1)

### Checking for missing values exclusively for each column

In [6]:
missing_values = df.isnull().sum()
print("Missing values per attribute:")
print(missing_values)

Missing values per attribute:
class     0
aa_000    0
ab_000    0
ac_000    0
ad_000    0
         ..
ee_007    0
ee_008    0
ee_009    0
ef_000    0
eg_000    0
Length: 171, dtype: int64


### Significant findings from preprocessing of data:
 - The size(shape) of the dataset helps you understand the data's volume.
 - Getting to know the datatypes of each feature can give you an idea of how to precede further calculations and manipulations of data.
 - Missing values indicate potential data quality issues that may require handling. Fortunately, no missing values found in any columns so no need to handle them.
 - The feature whose datatype is numerical is only 'aa_000'.

In [7]:
df.describe()

aa_000
count  6.000000e+04
mean   5.933650e+04
std    1.454301e+05
min    0.000000e+00
25%    8.340000e+02
50%    3.077600e+04
75%    4.866800e+04
max    2.746564e+06

### Enhancing EDA (Exploratory Data Analysis) with visualization of data.
- Importing vital libraries for visualization

In [8]:
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df['class'].value_counts()

class
neg    59000
pos     1000
Name: count, dtype: int64

- Histogram Plot

## Curse of Dimensionality
The Curse of Dimensionality refers to the challenges and problems that arise when dealing with high-dimensional data. It affects data analysis as follows:
 - As the number of dimensions increases, algorithms require more computational resources.
 - High-dimensional data can lead to overfitting in machine learning models.
 - It becomes harder to infer meaningful patterns with many dimensions.
 - Data points become more spread out, making it challenging to find neighbors or similarities.

One of the solutions to this curse is dimensionality reduction and this could be achieved by applying Principal Component Analysis (PCA) on dataset.

## Applying Principal Component Analysis (PCA) for Dimensionality Reduction.

### Importing necessary Libraries for PCA

In [11]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

### Applying label encoding on dataset to convert categorical features (string) to numerical classes. This is done to incorporate the whole data for further calculations

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for i in df.columns:
    df[i] = le.fit_transform(df[i])

### Standardization (mean centering and scaling to unit variance). Standardization ensures that all features have equal influence in the PCA analysis, and it helps in capturing the true variance of each feature.

In [13]:
scaler = StandardScaler()
data_standardized = scaler.fit_transform(df)
data_standardized

array([[-0.13018891,  1.19159108,  0.53075991, ..., -0.73351866,
        -0.22474038, -0.23069838],
       [-0.13018891, -0.00875114,  0.53075991, ..., -0.18281782,
        -0.22474038, -0.23069838],
       [-0.13018891,  0.36900137,  0.53075991, ...,  1.47847888,
        -0.22474038, -0.23069838],
       ...,
       [-0.13018891, -1.03091398, -1.98735109, ..., -0.73351866,
        -0.22474038, -0.23069838],
       [-0.13018891,  1.26738608,  0.53075991, ...,  1.12466072,
        -0.22474038, -0.23069838],
       [-0.13018891,  0.30802918,  0.53075991, ..., -0.11116648,
        -0.22474038, -0.23069838]])

### Applying PCA to transform the original data into a new set of orthogonal features (principal components) that explain the most variance in the data.

In [14]:
pca = PCA()
pca.fit(data_standardized)


PCA()

### Calculating the explained variance ratio tells us the proportion of the total variance in the data that is explained by each principal component, helping to understand the significance of each component.

In [15]:
explained_variance_ratio = pca.explained_variance_ratio_
explained_variance_ratio

array([1.33244725e-01, 6.79023540e-02, 5.93759898e-02, 4.96641181e-02,
       4.37523483e-02, 2.80370345e-02, 2.39090446e-02, 1.93514205e-02,
       1.69558886e-02, 1.42395333e-02, 1.37942134e-02, 1.22897537e-02,
       1.05263495e-02, 9.80522173e-03, 9.20516074e-03, 8.75267476e-03,
       8.37485445e-03, 8.27254678e-03, 7.76212003e-03, 7.57683685e-03,
       7.36066150e-03, 7.00418788e-03, 6.89101202e-03, 6.72106157e-03,
       6.38597174e-03, 6.29711295e-03, 6.13235750e-03, 6.06363742e-03,
       5.92637585e-03, 5.86462146e-03, 5.78668830e-03, 5.68400381e-03,
       5.58745557e-03, 5.55749602e-03, 5.49435565e-03, 5.39396148e-03,
       5.36021889e-03, 5.30258710e-03, 5.27876865e-03, 5.23287794e-03,
       5.16048310e-03, 5.11422473e-03, 5.05415365e-03, 5.00953699e-03,
       4.92879615e-03, 4.88535759e-03, 4.87263221e-03, 4.81969957e-03,
       4.80955745e-03, 4.69762761e-03, 4.65652734e-03, 4.60889029e-03,
       4.55634816e-03, 4.51717147e-03, 4.49225120e-03, 4.48047143e-03,
      

### By calculating the cumulative explained variance, we can determine the number of components required to retain a certain percentage of the total variance. In this case, we aim to retain 99.5% (as mentioned in assignment) of the variance, which balances dimensionality reduction and information preservation.

In [16]:
cumulative_explained_variance = np.cumsum(explained_variance_ratio)
num_components = np.argmax(cumulative_explained_variance >= 0.995) + 1
num_components

149

### Applying PCA on selected most significant components can lead to improved model performance, faster training times, and easier data interpretation.

In [17]:
pca = PCA(n_components=num_components)
data_reduced = pca.fit_transform(data_standardized)
data_reduced


array([[-3.30051431e-01,  1.90013155e-01, -2.47802259e+00, ...,
         1.43427963e-01, -5.12026333e-02, -1.81855258e-01],
       [ 9.88169318e-01, -5.72873802e-01, -5.56483540e+00, ...,
        -7.82852201e-02, -1.72154588e-02, -8.79750004e-02],
       [-3.51275762e+00, -3.48239574e-02, -9.40571863e-01, ...,
         1.55459322e-01, -9.05344745e-02, -4.27545254e-02],
       ...,
       [-1.09584681e+00,  4.55045208e-01,  4.46099209e+00, ...,
        -6.33088373e-02,  2.07164128e-01, -2.81228612e-01],
       [-7.40064322e-01,  3.89020552e-01, -1.41326726e+00, ...,
         4.11290980e-02,  1.24662174e-01, -6.43678849e-01],
       [-1.76892405e+00,  5.64375980e-01, -2.24915358e+00, ...,
         4.54404419e-03,  9.11644847e-02,  1.56842807e-02]])

## Results of PCA

In [18]:
print(f"Explained Variance Ratio: {explained_variance_ratio}")
print(f"Number of Components to Retain 99.5% Variance: {num_components}")
print(f"Reduced Data Shape: {data_reduced.shape}")

Explained Variance Ratio: [1.33244725e-01 6.79023540e-02 5.93759898e-02 4.96641181e-02
 4.37523483e-02 2.80370345e-02 2.39090446e-02 1.93514205e-02
 1.69558886e-02 1.42395333e-02 1.37942134e-02 1.22897537e-02
 1.05263495e-02 9.80522173e-03 9.20516074e-03 8.75267476e-03
 8.37485445e-03 8.27254678e-03 7.76212003e-03 7.57683685e-03
 7.36066150e-03 7.00418788e-03 6.89101202e-03 6.72106157e-03
 6.38597174e-03 6.29711295e-03 6.13235750e-03 6.06363742e-03
 5.92637585e-03 5.86462146e-03 5.78668830e-03 5.68400381e-03
 5.58745557e-03 5.55749602e-03 5.49435565e-03 5.39396148e-03
 5.36021889e-03 5.30258710e-03 5.27876865e-03 5.23287794e-03
 5.16048310e-03 5.11422473e-03 5.05415365e-03 5.00953699e-03
 4.92879615e-03 4.88535759e-03 4.87263221e-03 4.81969957e-03
 4.80955745e-03 4.69762761e-03 4.65652734e-03 4.60889029e-03
 4.55634816e-03 4.51717147e-03 4.49225120e-03 4.48047143e-03
 4.41373854e-03 4.38127991e-03 4.32542962e-03 4.29044471e-03
 4.25537226e-03 4.22220720e-03 4.16593664e-03 4.10374458e-0

## Summary
Principal Component Analysis (PCA) is a popular linear feature extractor used for unsupervised feature selection. PCA is used for dimensionality reduction in this analysis because it offers several benefits:

- **Reduced Dimensionality:** PCA transforms high-dimensional data into a lower-dimensional space while preserving as much variance as possible.
- **Improved Model Performance:** In many cases, reducing dimensionality with PCA can lead to better performance in machine learning models, as it reduces noise and multicollinearity.

By performing PCA and retaining 99.5% of the variance, we are ensuring that the most critical information is retained while reducing the data's complexity. The result, **data_reduced**, contains a reduced set of features that are most informative for further analysis or modeling.

## References

1. Scikit-learn Contributors. "Scikit-learn: Machine Learning in Python." [Scikit-learn Website](https://scikit-learn.org/stable/)

2. Seaborn Development Team. "Seaborn: Statistical Data Visualization." [Seaborn Website](https://seaborn.pydata.org/)

3. Matplotlib Development Team. "Matplotlib: Visualization with Python." [Matplotlib Website](https://matplotlib.org/)

4. Numpy Development Team. "Numpy: Scientific Computing." [Numpy Website](https://numpy.org//)

5. Pandas Development Team. "Pandas: Powerful data structures for data analysis, time series, and statistics." [Pandas Website](https://pandas.pydata.org/)